# Generated by Django 3.1.2 on 2021-04-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210423_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='bids_in_the_auction', to='auctions.Bid'),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_bid_for_the_listing', to='auctions.bid'),
        ),
    ]
