# Generated by Django 3.1.2 on 2021-05-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210503_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='item',
            new_name='items',
        ),
    ]
