# Generated by Django 3.1.2 on 2021-04-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conspi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='base',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='defenetely_false',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='defenetely_true',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='dont_know',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='probably_false',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='probably_true',
            field=models.IntegerField(),
        ),
    ]
