# Generated by Django 3.1.2 on 2021-04-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conspi', '0002_auto_20210411_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='defenetely_false',
            new_name='definitely_false',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='defenetely_true',
            new_name='definitely_true',
        ),
    ]
